[package]
name = "gitrs"
version = "0.1.0"
authors = ["cannero <serunmal@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
flate2 = "1.0"